### ISSUE TITLE
Inconsistent compilation bug

### ISSUE THREAD

**Issue by Thorinwasher** [stargate-bukkit/Stargate-Bukkit#23]
This get thrown at server ini:
----------------------------
[20:54:08 ERROR]: Error occurred while enabling Stargate v0.10.5.2 (Is it up to date?)
java.lang.NoClassDefFoundError: java/lang/constant/Constable
        at net.TheDgtl.Stargate.Stargate.loadAllPortals(Stargate.java:246) ~[?:?]
        at net.TheDgtl.Stargate.Stargate.onEnable(Stargate.java:165) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-468]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-468]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-468]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.5.jar:git-Paper-468]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.5.jar:git-Paper-468]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:465) ~[patched_1.16.5.jar:git-Paper-468]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.5.jar:git-Paper-468]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936) ~[patched_1.16.5.jar:git-Paper-468]        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-468]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.ClassNotFoundException: java.lang.constant.Constable
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_281]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:182) ~[patched_1.16.5.jar:git-Paper-468]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Paper-468]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
        ... 12 more

-------------------------------
How to recreate (might only be a thing from my setup): Compile the plugin, check if it works, if not, recompile it (redo this untill you get an error). Cleaning the target folder has always solved this issue for me, but that might be affirmative bias

No-one is really affected by this except for developers, as the plugin file works completely fine once it has been compiled properly. (extremely low priority)

**Comment by Thorinwasher** [comment]
Has not reoccurred
