### ISSUE TITLE
Error after using a networked gate

### ISSUE THREAD

**Issue by Thorinwasher** [stargate-bukkit/Stargate-Bukkit#59]
What I remember, I did this: 
- Create two networked portals
- For one of the portals (can't remember if it was the first or second one) chose the other as destination
- Walk into the iris / portal entrance

After I entered the portal iris, an error got thrown. When I redid this with the same portals, nothing happened, neither could I reproduce it if I made new portals / tried to replicate the exact way of events.
#### Stack trace
[16:59:23] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Stargate v0.11.0.3
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.17.jar:3170-Spigot-a483d2c-ec116f6]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.17.jar:3170-Spigot-a483d2c-ec116f6]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.17.jar:3170-Spigot-a483d2c-ec116f6]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.17.jar:3170-Spigot-a483d2c-ec116f6]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1252) ~[spigot-1.17.jar:3170-Spigot-a483d2c-ec116f6]
        at net.minecraft.network.protocol.game.PacketPlayInFlying.a(SourceFile:114) ~[spigot-1.17.jar:3170-Spigot-a483d2c-ec116f6]
        at net.minecraft.network.protocol.game.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:16) ~[spigot-1.17.jar:3170-Spigot-a483d2c-ec116f6]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[spigot-1.17.jar:3170-Spigot-a483d2c-ec116f6]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.17.jar:3170-Spigot-a483d2c-ec116f6]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[spigot-1.17.jar:3170-Spigot-a483d2c-ec116f6]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.17.jar:3170-Spigot-a483d2c-ec116f6]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[spigot-1.17.jar:3170-Spigot-a483d2c-ec116f6]
        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1125) ~[spigot-1.17.jar:3170-Spigot-a483d2c-ec116f6]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1118) ~[spigot-1.17.jar:3170-Spigot-a483d2c-ec116f6]
        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(SourceFile:134) ~[spigot-1.17.jar:3170-Spigot-a483d2c-ec116f6]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1102) ~[spigot-1.17.jar:3170-Spigot-a483d2c-ec116f6]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1031) ~[spigot-1.17.jar:3170-Spigot-a483d2c-ec116f6]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[spigot-1.17.jar:3170-Spigot-a483d2c-ec116f6]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.TheDgtl.Stargate.portal.Network$Portal.getExit()" because "desti" is null
        at net.TheDgtl.Stargate.listeners.MoveEventListener.onPlayerMove(MoveEventListener.java:69) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor10.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.17.jar:3170-Spigot-a483d2c-ec116f6]
        ... 18 more

**Comment by Thorinwasher** [comment]
Note to self:
If issue can not be reproduced within 2 weeks, close it

**Comment by Thorinwasher** [comment]
Removed per the above comment
